name: express
recipe: drupal7
config:
  webroot: web
  # Remove XDebug for speed improvements.
  xdebug: true
  php: "7.1"
  #conf:
    #php: config/php/zzzzzz-express-custom.ini
services:
  appserver:
    extras:
      # Install Vim for debugging.
      #- apt-get update
      #- apt-get install vim
      - wget -O - https://packagecloud.io/gpg.key | apt-key add -
      - echo "deb http://packages.blackfire.io/debian any main" | tee /etc/apt/sources.list.d/blackfire.list
      - apt-get update
      - apt-get install blackfire-agent
      - blackfire-agent -register --server-id="${BLACKFIRE_ID}" --server-token="${BLACKFIRE_TOKEN}"
      - /etc/init.d/blackfire-agent restart
      - apt-get install blackfire-php
    overrides:
      services:
        environment:
          DSLM_BASE: '/app/code/dslm_base'
          PACKAGES_BASE: '/app/code/packages_base'
          LANDO_ENV: 'yes'
          BLACKFIRE_ID: '8b305f5c-67ef-478a-9c0a-fcaed63b1783'
          BLACKFIRE_TOKEN: '5feef8704db3271c6dd3fa6bcf4c7232bfa50a02979ff0f0f03234340c37193e'
  database:
    portforward: 3308
tooling:
  create-site:
    service: appserver
    cmd:
      - "./scripts/create-site.sh"
  add-tools:
    service: appserver
    cmd:
      - "./scripts/add-tools.sh"
  test:
    service: appserver
    cmd:
      - "./scripts/test.sh"
