os: osx

install:
  - brew install homebrew/php/php72
  - brew install composer
  - composer global require laravel/valet
  - valet install

script:
  # See if NGINX responds.
  # - ping foobar.test

  # Run setup script.
  - ./travis-setup.sh

