os: osx

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.drush/cache
    - $HOME/cache

before_install:
  # Install dependencies.
  - brew install homebrew/php/php71
  - brew install composer
  - brew install mysql
  - composer global require laravel/valet "drush/drush:8.*" -v

  # Need to export Composer path.
  - echo $USER
  - ls -al /Users/$USER
  - echo "export PATH='/Users/${USER}/.composer/vendor/bin:$PATH'" >> ~/.bash_profile
  - source ~/.bash_profile

  # Install Valet.
  - valet install

script:
  # See if NGINX responds.
  # - ping foobar.test

  # Start MySQL.
  - brew services start mysql

  # Run setup script.
  - ./travis-setup.sh

